server:
  port: 9090

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**

handlebars:
  enabled: true
  cache: false
  prefix: classparh:templates/
  suffix: .hbs